# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            iMega's Blog
tagline:          This notebook
url:              http://imega.ru
paginate:         3
baseurl:          /
author:
  name:           Dmitry Gavriloff
  url:            http://imega.ru
  email:          info@imega.ru

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/iMega
